### ISSUE TITLE
Update scope unit tests to new config model

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4.EntityFramework#36]
For now they got commented out

**Comment by brockallen** [comment]
I'm happy for you to look into this @scottbrady91 :)

**Comment by scottbrady91** [comment]
I'm on it. Give me a heads up before you go live.

**Comment by scottbrady91** [comment]
Done in 43c3291

**Comment by brockallen** [comment]
thanks!

**Comment by brockallen** [comment]
Is there some change in the setup? I ran them locally, but I don't think the DB was auto-created.

**Comment by scottbrady91** [comment]
I updated the test runners to use .NET Core 1.0.1 trying to fix a rider issue.

**Comment by brockallen** [comment]
```
Test Name:	IdentityServer4.EntityFramework.IntegrationTests.Stores.ScopeStoreTests.FindApiResourceAsync_WhenResourceExists_ExpectResourceAndCollectionsReturned
Test FullName:	IdentityServer4.EntityFramework.IntegrationTests.Stores.ScopeStoreTests.FindApiResourceAsync_WhenResourceExists_ExpectResourceAndCollectionsReturned
Test Source:	C:\ballen\github\identity\IdSvr4\EntityFramework\test\IdentityServer4.EntityFramework.IntegrationTests\Stores\ResourceStoreTests.cs : line 176
Test Outcome:	Failed
Test Duration:	0:00:00.356

Result1 Name:	IdentityServer4.EntityFramework.IntegrationTests.Stores.ScopeStoreTests.FindApiResourceAsync_WhenResourceExists_ExpectResourceAndCollectionsReturned
Result1 Outcome:	Failed
Result1 Duration:	0:00:00.025
Result1 StackTrace:	
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at IdentityServer4.EntityFramework.IntegrationTests.Stores.ScopeStoreTests.FindApiResourceAsync_WhenResourceExists_ExpectResourceAndCollectionsReturned(DbContextOptions`1 options) in C:\ballen\github\identity\IdSvr4\EntityFramework\test\IdentityServer4.EntityFramework.IntegrationTests\Stores\ResourceStoreTests.cs:line 182
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
Result1 Message:	
An error occurred while updating the entries. See the inner exception for details.
SQLite Error 1: 'no such table: ApiResources'.

Result2 Name:	IdentityServer4.EntityFramework.IntegrationTests.Stores.ScopeStoreTests.FindApiResourceAsync_WhenResourceExists_ExpectResourceAndCollectionsReturned
Result2 Outcome:	Passed
Result2 Duration:	0:00:00.135
Result2 StackTrace:
Result2 Message:

Result3 Name:	IdentityServer4.EntityFramework.IntegrationTests.Stores.ScopeStoreTests.FindApiResourceAsync_WhenResourceExists_ExpectResourceAndCollectionsReturned
Result3 Outcome:	Passed
Result3 Duration:	0:00:00.196
Result3 StackTrace:
Result3 Message:


```

**Comment by brockallen** [comment]
Hmm, interesting... I ran then again and now they all pass.

**Comment by scottbrady91** [comment]
Sounds like the databases didn't tear down after one of the tests ran.

**Comment by brockallen** [comment]
Ok, 3 clean runs in a row -- good enough for me :)

Thanks.

**Comment by scottbrady91** [comment]
:shipit:
