### ISSUE TITLE
Problem with DI after migrating to Asp.Net Core 2.0

### ISSUE THREAD

**Issue by Arkatufus** [IdentityServer/IdentityServer4.EntityFramework#98]
I'm getting this exception after upgrading to Asp.Net Core 2.0 and IdentityServer4.EntityFramework 2.0.0-rc1:
```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'Microsoft.Extensions.DependencyInjection.IIdentityServerBuilder Microsoft.Extensions.DependencyInjection.IdentityServerEntityFrameworkBuilderExtensions.AddConfigurationStore(Microsoft.Extensions.DependencyInjection.IIdentityServerBuilder, System.Action`1<IdentityServer4.EntityFramework.Options.ConfigurationStoreOptions>)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Agate.Onyx.OpenId.Startup.ConfigureServices(IServiceCollection services) in C:\Work\git\onyx\src\onyx-openid-server\Startup.cs:line 109
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Agate.Onyx.OpenId.Program.BuildWebHost(String[] args) in C:\Work\git\onyx\src\onyx-openid-server\Program.cs:line 28
   at Agate.Onyx.OpenId.Program.Main(String[] args) in C:\Work\git\onyx\src\onyx-openid-server\Program.cs:line 17
```

I've done a full Asp.Net Core 2.0 migration as per https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/
This is what I use to configure the configuration store:
```
var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
IIdentityServerBuilder identityService = services.AddIdentityServer();
identityService.AddConfigurationStore(opt =>
    opt.ConfigureDbContext = builder =>
    {
        builder.UseMySql("mysql connection string here",
            options => options.MigrationsAssembly(migrationsAssembly));
    });
```

**Comment by Arkatufus** [comment]
This problem also stops me from running entity framework add migration and database update

**Comment by idwebmedia** [comment]
Same here. I know Brock said he was going to start focusing on EF so hopefully we'll have something soon.

**Comment by Arkatufus** [comment]
Deleting the bin and obj folder, and then restoring the nuget packages fixed this problem for me.
Closing this issue for now.
